export const environment = {
  production: true,
  Razorpay_test_key:'rzp_test_GxaJhvoS78ZpIz',
  Razorpay_live_key:'rzp_test_Z6PoT6HRL71TiC',
  // live_url: 'https://projectacedev.thestorywallcafe.com/api',
   //media_url: 'https://projectacedev.thestorywallcafe.com/media',
   
  media_url: 'https://projectacedevelop.thestorywallcafe.com',
  live_url:'https://projectacedevelop.thestorywallcafe.com/api',
  socket_url:'projectacedevelop.thestorywallcafe.com',
 
  // live_url: 'https://projectacetest.thestorywallcafe.com/api',
  // media_url:'https://projectacetest.thestorywallcafe.com',
  // socket_url:'projectacetest.thestorywallcafe.com',
 
  // live_url: 'https://app.projectace.in/api',
  // media_url: 'https://app.projectace.in',
  // socket_url:'app.projectace.in',

  // live_url: 'https://projectaceprod.thestorywallcafe.com/api',
  // media_url: 'https://projectaceprod.thestorywallcafe.com/media',

  // live_url: 'https://projectaceuat.thestorywallcafe.com/api',
  // media_url: 'https://projectaceuat.thestorywallcafe.com',
  // socket_url:'projectaceuat.thestorywallcafe.com',

  // live_url: 'https://projectaceprod.thestorywallcafe.com/api',
  // media_url: 'https://projectaceprod.thestorywallcafe.com/media',
  leave_application: 'leave-application',
  timesheetCalender: 'time-sheets-calender',
  taskProjectCategories: 'task-project-categories',
  users_leave_details: `users-leave-details`,
  get_time_sheet_values: `get-time-stamp-values`,
  managerReview: `manager-review`,
  add_on_leave_request: `add-on-leave-request`,
  organization: `organization`,
  userRole: `user-role`,
  office_working_days: `office-working-days`,
  profile_custom_user: `profile-custom-user`,
  time_sheets: `timesheets`,
  time_sheets_deadline_crossed: `time-sheets-deadline-crossed`,
  time_sheets_monthly: `time-sheets-monthly`,
  country_state_city: `country-state-city`,
  people_list: `people`,
  prefix_suffix: `prefix-suffix`,
  center_list: `center`,
  tag: `tag`,
  master_leave_list: `master-leave-types`,
  type_of_industries: `type-of-industries`,
  main_category: `project-status-main-category`,
  sub_category: `project-status-sub-category`,
  project_tasks: `task-project-categories`,
  project_list: `projects`,
  org_department: `organization-department`,
  approval_config: `time-sheets-approval-config`,
  notification: `get-notification`,
  update_notification: `update-seen-notification`,
  timesheets: `timesheets`,
  country:`country`,
  state:`state`,
  city:`city`,
  client:`client`,
  leave_master:`leave-master`,
  employee_leaves:`employee-leaves`,
  all_employee:`all-employee`,
  apply_leave:`apply-leave`,
  employee_leave_details:`employee-leave-details`,
  project:`project`,
  project_task:`project-task`,
  task_hours:`timesheet-task-hours`,
  update_timesheet_status:`update-timesheet-status`,
  update_leave_details:`update-leave-details`,
  allEmployee:`all-employee`,
  working_hour:`working-hour`,
  designation:`designation`,
  department:`department`,
  user:`user`,
  holiday_calender:`upload-holiday-calender`,
  project_template:`project_category`,
  timesheet_comment:`timesheet-comment`,
  leave_comment:`leave-comment`,
  subscription_list:`subscription-list`,
  my_subscription:`my-subscription`,
  transaction_history:`transaction-history`,
  configure_subscription:`configure-subscription`,
  buy_subscription:`buy-subscription`,
  cancel_my_subscription:`cancel-my-subscription`,
  plan_types:`plan-types`,
  working_hour_config: `super-admin-conf-working-hour`
};